### ISSUE TITLE
Problema com AttributeDto do tipo "Function(bool)".

### ISSUE THREAD

**Issue by JoaoPaulo-Macedo** [jheimes-silveira/storybook_ds#2]
Quando é passado o tipo "Function(bool)" pro AttributeDto, o ContentWidget é forçado a percorrer a lista de VariableOptions, mesmo que essa não tenha sido definida. Tirando o tipo "bool" da String de "Function()", o ContentWidget volta ao seu comportamento esperado.

Erro:

> Unexpected null value.
> The relevant error-causing widget was:
> ContentWidget
> ContentWidget: .../lib/src/storybook.dart:44:14

Quebra na linha: .../lib/src/widgets/content_widget.dart:343

**Comment by jheimes-silveira** [comment]
Correção feita na nova versão
